# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'Compute
#'@param x a vector
#'@export
timesTwo <- function(x) {
    .Call(`_formationHeavyr_timesTwo`, x)
}

#'Compute inverse matrix in c++
#'@param A a matrix
#'
#'@export
invC <- function(A) {
    .Call(`_formationHeavyr_invC`, A)
}

